# Generated by Django 4.0.3 on 2022-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
